apiVersion: v1
kind: Namespace
metadata:
  name: alex-n8n
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: alex-monaco-beaute
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
